name: Run Screener Daily

on:
  schedule:
    - cron: '0 10 * * *'  # 每天 UTC 10 點，台灣 6PM
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas scipy gspread oauth2client
          pip install git+https://github.com/twopirllc/pandas-ta.git@master

      - name: Write credentials file from secret
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

      - name: Run Screener
        run: |
          python call_option_screener.py

